const mockData = [
  {
    product_id: 1,
    username: 'W C',
    comment: 'These go well with any types of clothes! Honestly, I got them for myself for Christmas, and I have been wearing them ever since',
    verified: true,
    locale: 'US',
    upvote: 5,
    downvote: 0,
    created_at: 'Oct 29, 2020',
    size_rating: 3,
    durability_rating: 3,
    comfort_rating: 3,
    stars: 3,
    product_name: 'Nike 1',
    comfort_average: 3,
    durability_average: 3,
    size_average: 3,
    stars_average: 3,
  },
  {
    product_id: 1,
    username: 'Mark',
    comment: 'They wore out after a month of using them. The durability is not okay, hopefully they will upgrade these shoes.',
    verified: false,
    locale: 'US',
    upvote: 5,
    downvote: 0,
    created_at: 'Aug 27, 2020',
    size_rating: 3,
    durability_rating: 2,
    comfort_rating: 3,
    stars: 3,
    product_name: 'Nike 1',
    comfort_average: 3,
    durability_average: 3,
    size_average: 3,
  },
  {
    product_id: 1,
    username: 'Alice',
    comment: 'Looks great, feels great. These pair of shoes are worth the money.',
    verified: true,
    locale: 'US',
    upvote: 5,
    downvote: 0,
    created_at: 'Mar 27, 2020',
    size_rating: 5,
    durability_rating: 4,
    comfort_rating: 3,
    stars: 3,
    product_name: 'Nike 1',
    comfort_average: 3,
    durability_average: 3,
    size_average: 3,
  },
  {
    product_id: 1,
    username: 'Yu',
    comment: 'Great fit! The durability is amazing as well. Bought it for myself as I needed a pair of running shoes! Definitely a must buy.',
    verified: true,
    locale: 'US',
    upvote: 5,
    downvote: 0,
    created_at: 'Aug 27, 2020',
    size_rating: 3,
    durability_rating: 3,
    comfort_rating: 3,
    stars: 3,
    product_name: 'Nike 1',
    comfort_average: 3,
    durability_average: 3,
    size_average: 3,
  }
];

export default mockData;