const testData = [
  {
    product_id: 1,
    username: 'Bot 1',
    comment: 'Uh-oh. Unfortunately the review you are looking for cannot be found! Please try again later',
    verified: false,
    locale: 'US',
    upvote: 5,
    downvote: 0,
    created_at: 'Oct-29-2020',
    size_rating: 3,
    durability_rating: 3,
    comfort_rating: 3,
    stars: 3,
    product_name: 'Nike 1',
    comfort_average: 3,
    durability_average: 3,
    size_average: 3,
    stars_average: 3,
  },
  {
    product_id: 1,
    username: 'Bot 2',
    comment: 'Uh-oh. Unfortunately the review you are looking for cannot be found! Please try again later',
    verified: false,
    locale: 'US',
    upvote: 5,
    downvote: 0,
    created_at: 'Aug-27-2020',
    size_rating: 3,
    durability_rating: 3,
    comfort_rating: 3,
    stars: 3,
    product_name: 'Nike 1',
    comfort_average: 3,
    durability_average: 3,
    size_average: 3,
  },
  {
    product_id: 1,
    username: 'Bot 3',
    comment: 'Uh-oh. Unfortunately the review you are looking for cannot be found! Please try again later',
    verified: false,
    locale: 'US',
    upvote: 5,
    downvote: 0,
    created_at: 'Mar-27-2020',
    size_rating: 3,
    durability_rating: 3,
    comfort_rating: 3,
    stars: 3,
    product_name: 'Nike 1',
    comfort_average: 3,
    durability_average: 3,
    size_average: 3,
  },
  {
    product_id: 1,
    username: 'Bot 4',
    comment: 'Uh-oh. Unfortunately the review you are looking for cannot be found! Please try again later',
    verified: false,
    locale: 'US',
    upvote: 5,
    downvote: 0,
    created_at: 'Aug-27-2020',
    size_rating: 3,
    durability_rating: 3,
    comfort_rating: 3,
    stars: 3,
    product_name: 'Nike 1',
    comfort_average: 3,
    durability_average: 3,
    size_average: 3,
  }
];

export default testData;